name: Docker bicep app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo 
      uses: actions/checkout@v2
      
    - name: Azure CLI 
      uses: azure/login@v1
      with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Docker 
      uses: azure/docker-login@v1
      with:
        login-server: <your-acr-login-server>.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    

    - name: Deploy Bicep App 
      run:
        az deployment group create \
          --resource-group aguadamillas_students_1 \
          --template-file ./main.bicep \
          --parameters @parameters.json \
          --parameters DOCKER_REGISTRY_SERVER_URL=${{ vars.DOCKER_REGISTRY_SERVER_URL }} \
          --parameters DOCKER_REGISTRY_SERVER_USERNAME=${{ vars.DOCKER_REGISTRY_SERVER_USERNAME }} \
          --parameters DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}